language: node_js
node_js:
  - "4"
addons:
  firefox: "latest"
before_script:
  - export CHROME_URL=https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64
  - export CHROME_REV=$(curl -s ${CHROME_URL}/LAST_CHANGE)
  - curl ${CHROME_URL}/${CHROME_REV}/chrome-linux.zip --create-dirs -o out/chrome-linux.zip
  - unzip out/chrome-linux.zip -d out
  - ln -s out/chrome-linux/chrome out/chrome-linux/google-chrome
  - export PATH=out/chrome-linux/:$PATH
  - npm install --quiet web-component-tester bower
  - export PATH=$PWD/node_modules/.bin:$PATH
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: "wct -l firefox -l chrome"
sudo: false
