language: node_js
node_js:
  - "4"
addons:
  firefox: "latest"
before_script:
  - "npm install --quiet web-component-tester bower"
  - "export PATH=$PWD/node_modules/.bin:$PATH"
  - "bower install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
script: "wct -l firefox"
sudo: false
