language: node_js
node_js:
  - "4"
addons:
  firefox: "latest"
before_script:
  - |
    mkdir .chrome
    pushd .chrome
    ln -s `which chromium-browser` google-chrome
    export PATH=$PWD:$PATH
    popd
    which google-chrome
    npm install --quiet web-component-tester bower
    export PATH=$PWD/node_modules/.bin:$PATH
    bower install
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
script: "wct -l firefox -l chrome"
sudo: false
