language: node_js

node_js:
  - "4"

addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm install web-component-tester bower
  - export PATH=$PWD/node_modules/.bin:$PATH
  - bower install

script: xvfb-run -a wct --simpleOutput -l firefox -l chrome

sudo: false
