language: node_js

node_js:
  - "4"

addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm install --quiet web-component-tester bower
  - export PATH=$PWD/node_modules/.bin:$PATH
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: wct --simpleOutput -l firefox -l chrome

sudo: false
