language: node_js
node_js:
- '4'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
  - xvfb-run -a wct --simpleOutput -l firefox -l chrome
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
      wct --simpleOutput -s 'Windows 10/microsoftedge' -s 'Windows 8.1/internet explorer@11' -s 'Windows 7/internet explorer@10' -s 'OS X 10.10/safari@8' -s 'OS X 10.9/safari@7'
    fi
sudo: false
env:
  global:
  - secure: JfC9zSG3lwqx11LGcdom3IXoSm9iJWOBjBS8d15bAzNJGcj5BSAXLNiOdLnayrF0Az/FVclVqYEp55Vg7rRC6P1Jc2dFNw5O3WeodnkZFHrOrTS/Hzz0iQDQa8U2+7fmZ9nqfvphAEefOHDsxPJ5hHUsee/Ygf8k1L3TUof5HLAfrgw1tPuSAPCvgL7gtR5q8P+I0sEOsgo+xh9pl85256l2QrWS7c9R9SNoYBBWc76K2oZaYq8jpiae7ah1DRaqqLl4ZtDdUjC4y2JQ7qFh+m0ukRsqKhJwf4HC4UXBCUybZ/V5H2akUbZE0r0xMPx5BL8n9yL27vEt/BgkIU8O2A+wOZTa72UiYaCt/ADrXkHAhaXBx4qnA9O9DOwyZ3HJh6rpZKf3c/JrjmWfh9NYD1H/+asbBb5bagsq4W1lQSOeZc/eu7f7eeU37GvNb5UGUlIaSWq+dqe0j7YVakW5H31jbAiybBikjIBVzmmXHQW1XXo1SMMXs8Vy034RfytWdOZrkBfMqnjd4dKm5x1ld/mPgcMB5V+gDdvqjiW3JSgC5DN/ipSpNbsKWagYrApBQbxDqwL+SzSkDgoPaYR4K/+PtHu+pZego+XAwhF+bCXTTe7hvY/hFYFqIHN6W4FBksNUKA39Paay/BHfN/FJdgCRktDnx04OSKTTQ5gvraE=
  - secure: l8SqBemzDeQQPjrO3MNqOBpxeCJ8Wd2JTlQEdAQi377PpbCL7qAxOj31oWjlxm+n67waJbROnzNUTTHnQ+1TVWJHe0bAPZjex2nV/oDA63OICZdaPllov4F04FaS6SV+t3KsjiR31AGwVEu8uiD+boC2vCmIaFmbwOXTaghvnpe5VfSO3idLlxx5vpbeeOmrLiF1jfO9GAgDjZ7R9VC4xHWq65B3sbPdEhntkcUisOP8eT2dtg5mj0JWYJDe86R4o2KTq4ghx5SbW0beacOagv/0To1c7+LNgruiNsXZNXiz4L3bcBm3E80D2oilg/9aD1zdfq4Jj9QNx0+S5rRi0C+sfehDN9Cv0ef4b7j4hF1/Jt5Iwp75b4QYjlgqL1fO1QXBtuNzQxD4cMB+T2UPCgM7k2pqbFLM5Envv85+qL3gZYDk+bzXrZ8P0DM4CrxRzpRwSPOm0qCJQNUpth4lbAOcoioEgP79WRpGzya7unPtLn581WDPe9dGcXNpAjiF/+oojp3mJ1wwOMo4Dw4igkZGY01EK7nGlh5kwXjQopKlA1567u2i67nZJY3WDI7qdvaxEiKDn9IByUq71EU+CV2EMBb776Mfa/ylxe4gQFYfbgcC9meY1HkOAoG2ERBGKYe3+XrL+d1fM0P8aHUAedcFLZ/lq7kiZ/dSgU+DL4s=
